<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{{ title }} — Drupal JS API</title>

  <link type="text/css" rel="stylesheet" href="pure/pure.css">
  <link type="text/css" rel="stylesheet" href="styles/prettify-jsdoc.css">
  <link type="text/css" rel="stylesheet" href="styles/drupal.css">

  <script src="scripts/prettify/prettify.js"></script>
  <script src="scripts/prettify/lang-css.js"></script>
</head>

<body>

<div id="main" class="pure">


  <div class="pure-g">
    <div class="pure-u-4-5">
      <div class="box">
        <h1 class="page-title">{{ title }}</h1>
        {{ content }}
      </div>
    </div>

    <nav class="pure-u-1-5">
      <div class="box">{{ nav }}</div>
    </nav>
  </div>

</div>

<script> prettyPrint(); </script>
<script src="scripts/linenumber.js"></script>
</body>
</html>
